set nocompatible
syntax on
set history=100
set autoindent
set smartindent
set cindent
"检查文件类型
filetype on 
filetype plugin on 
filetype indent on
set tabstop=4
set shiftwidth=4
"设置编码
set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936
set fileencoding=utf-8


